window.PORTFOLIO_LANG = {
  en: {
    skip: "Skip to content",
    menuOpen: "Open navigation menu",
    menuClose: "Close navigation menu",
    themeToggle: "Switch color theme",
    languageGroup: "Choose language",
    backToTop: "Back to top",
    statsLabel: "Quick portfolio facts",
    filterLabel: "Filter projects",
    projectPreviewLabel: "Bean Boutique project preview",
    mapTitle: "Coffee shops in Yangon map",
    heroAlt: "Portrait of Aung Set Paing wearing glasses and a black shirt",
    aboutAlt: "Aung Set Paing outdoors in sunglasses",
    navAbout: "About",
    navSkills: "Skills",
    navProjects: "Projects",
    navEducation: "Education",
    navContact: "Contact",
    heroEyebrow: "Junior Developer · Full-stack focus",
    heroGreeting: "Hello, I'm",
    heroRolePrefix: "I build as a",
    roleJunior: "Junior Developer",
    roleFullstack: "Full-stack Developer",
    roleWeb: "Web Developer",
    heroDescription:
      "Curious about how things work, committed to making the web useful, clear and a little more human.",
    viewProjects: "View projects",
    downloadCv: "Download CV",
    contactMe: "Contact me",
    openToWork: "Open to internships",
    location: "Based in Myanmar",
    portraitCaption: "A little about me",
    learning: "Always learning",
    learningCaption: "One build at a time",
    scrollExplore: "Scroll to explore",
    aboutEyebrow: "A bit about me",
    aboutTitle: "Building my way forward.",
    photoLabel: "Curiosity looks good on me",
    aboutBio:
      "I'm a junior developer with a full-stack focus, learning by building and refining real web experiences. I'm currently studying for an NCC Education Level 4 Diploma in Computing and looking for an internship or junior role where I can grow with a team.",
    factOne: "Learning by doing",
    factTwo: "Full-stack curious",
    factThree: "Ready to collaborate",
    statTechnologies: "Technologies in my toolkit",
    statProject: "Featured project",
    statLanguages: "Site languages",
    statQualification: "Computing diploma",
    skillsEyebrow: "What I work with",
    skillsTitle: "Tools for the whole stack.",
    skillsAside: "A growing toolkit, backed by hands-on practice.",
    frontend: "Frontend",
    frontendDesc: "Interfaces with clear structure and responsive layouts.",
    backend: "Backend",
    backendDesc: "Learning the logic that makes useful products work.",
    database: "Database",
    databaseDesc: "Working with structured data and SQL foundations.",
    projectsEyebrow: "Selected work",
    projectsTitle: "Made with intent.",
    filterAll: "All",
    filterFrontend: "Frontend",
    filterFullstack: "Full-stack",
    previewKicker: "SLOW MORNINGS, GOOD COFFEE",
    previewShop: "Explore the menu",
    previewMatch: "YOUR MOOD, YOUR CUP",
    previewBrewMatch: "Meet your<br>BrewMatch.",
    previewFind: "Find your coffee",
    previewCart: "FRESHLY PICKED",
    previewCartTitle: "A little<br>something.",
    previewCartCta: "Your basket · 02",
    previousPreview: "Previous project preview",
    nextPreview: "Next project preview",
    mapCaption: "A little local flavour, via Google Maps",
    featuredLabel: "Featured case study",
    projectDescription:
      "A multi-page coffee shop experience, built to make finding a new favourite feel as good as the first sip.",
    featureDiscount: "Discount modal and feature carousel",
    featureCart: "Interactive cart and responsive navigation",
    featureBrew: "BrewMatch mood-based coffee finder",
    featureMap: "Google Maps embed",
    githubCode: "GitHub",
    liveDemoSoon: "Live demo soon",
    comingSoon: "Coming soon",
    nextBuildOne: "A new idea is brewing.",
    nextBuildOneDesc: "The next project is taking shape. Check back soon.",
    nextBuildTwo: "Something thoughtful.",
    nextBuildTwoDesc: "Another small build, with care in every detail.",
    educationEyebrow: "The foundation",
    educationTitle: "Learning never ships once.",
    educationLabel: "Education",
    educationTimelineLabel: "Education history",
    level5Title: "NCC Education Level 5, Cyber Security",
    educationInProgress: "In progress",
    level4Title: "NCC Education Level 4 Diploma in Computing",
    educationCompleted: "Completed",
    contactEyebrow: "Let's make something useful",
    contactTitle: "Good work starts<br>with a hello.",
    contactDescription:
      "I'm looking for an internship or junior developer role. Have a project or opportunity in mind? I'd love to hear about it.",
    sendEmail: "Send me an email",
    findMe: "Find me around the web",
    emailLabel: "Email",
    copyEmail: "Copy email address",
    copiedToast: "Email copied to clipboard",
    footerText: "Designed and built with curiosity.",
    footerRights: "All rights reserved.",
  },
  my: {
    skip: "အကြောင်းအရာသို့ ကျော်ရန်",
    menuOpen: "လမ်းညွှန်မီနူး ဖွင့်ရန်",
    menuClose: "လမ်းညွှန်မီနူး ပိတ်ရန်",
    themeToggle: "အရောင်အပြင်အဆင် ပြောင်းရန်",
    languageGroup: "ဘာသာစကား ရွေးချယ်ရန်",
    backToTop: "စာမျက်နှာထိပ်သို့ ပြန်သွားရန်",
    statsLabel: "Portfolio အချက်အလက်များ",
    filterLabel: "ပရောဂျက်များ စစ်ထုတ်ရန်",
    projectPreviewLabel: "Bean Boutique ပရောဂျက် အစမ်းမြင်ကွင်း",
    mapTitle: "ရန်ကုန်မြို့ရှိ ကော်ဖီဆိုင်များ မြေပုံ",
    heroAlt:
      "မျက်မှန်နှင့် အနက်ရောင်အင်္ကျီ ဝတ်ဆင်ထားသော Aung Set Paing ၏ ပုံတူဓာတ်ပုံ",
    aboutAlt: "နေကာမျက်မှန်တပ်၍ အပြင်ဘက်တွင်ရှိနေသော Aung Set Paing",
    navAbout: "မိတ်ဆက်",
    navSkills: "ကျွမ်းကျင်မှုများ",
    navProjects: "ပရောဂျက်များ",
    navEducation: "ပညာရေး",
    navContact: "ဆက်သွယ်ရန်",
    heroEyebrow: "Junior Developer · Full-stack ကို အာရုံစိုက်",
    heroGreeting: "မင်္ဂလာပါ၊ ကျွန်တော်က",
    heroRolePrefix: "ကျွန်တော်က",
    roleJunior: "junior Developer",
    roleFullstack: "Full-stack Developer",
    roleWeb: "ဝဘ်ဆိုက် Developer",
    heroDescription:
      "အရာတွေ ဘယ်လိုအလုပ်လုပ်သလဲဆိုတာ စူးစမ်းရတာနှစ်သက်ပြီး အသုံးဝင်၊ ရှင်းလင်းတဲ့ ဝဘ်အတွေ့အကြုံတွေ ရရှိိုဖို ကြိုးစားနေပါတယ်။",
    viewProjects: "ပရောဂျက်များကြည့်ရန်",
    downloadCv: "CV ဒေါင်းလုဒ်",
    contactMe: "ဆက်သွယ်ရန်",
    openToWork: "အလုပ်သင်အခွင့်အလမ်းများ လက်ခံနေပါသည်",
    location: "မြန်မာနိုင်ငံတွင် အခြေစိုက်",
    portraitCaption: "ကျွန်တော့်အကြောင်း အနည်းငယ်",
    learning: "အမြဲလေ့လာနေပါတယ်",
    learningCaption: "တစ်ခုချင်း တည်ဆောက်ရင်း",
    scrollExplore: "ဆက်လက်ကြည့်ရှုရန်",
    aboutEyebrow: "ကျွန်တော့်အကြောင်း",
    aboutTitle: "ရှေ့ဆက်ဖို့ တည်ဆောက်နေပါတယ်။",
    photoLabel: "စူးစမ်းလိုစိတ်က ကျွန်တော့်ကို ပိုလှစေပါတယ်",
    aboutBio:
      "ကျွန်တော်က Full-stack ကို အာရုံစိုက်လေ့လာနေတဲ့ Junior Developer တစ်ယောက်ပါ။ လက်တွေ့ဝဘ်အတွေ့အကြုံတွေ တည်ဆောက်ရင်း ပိုကောင်းအောင် ပြုပြင်ရင်း သင်ယူနေပါတယ်။ လက်ရှိမှာ NCC level 5 diploma in computing with cyber security ကို သင်ယူနေပြီး အသင်းနဲ့အတူ တိုးတက်နိုင်မယ့် အလုပ်သင် သို့မဟုတ် Junior ရာထူးကို ရှာဖွေနေပါတယ်။",
    factOne: "လက်တွေ့လုပ်ရင်း သင်ယူခြင်း",
    factTwo: "Full-stack ကို စူးစမ်းခြင်း",
    factThree: "အတူတကွ လုပ်ဆောင်ရန် အသင့်",
    statTechnologies: "အသုံးပြုလေ့လာနေသော နည်းပညာများ",
    statProject: "အဓိက ပရောဂျက်",
    statLanguages: "ဝဘ်ဆိုက် ဘာသာစကားများ",
    statQualification: "Computing ဒီပလိုမာ",
    skillsEyebrow: "အသုံးပြုနေသော နည်းပညာများ",
    skillsTitle: "Stack တစ်ခုလုံးအတွက် ကိရိယာများ။",
    skillsAside: "လက်တွေ့လေ့ကျင့်မှုနဲ့အတူ တိုးတက်လာနေတဲ့ နည်းပညာစုစည်းမှု။",
    frontend: "Frontend",
    backend: "Backend",
    database: "Database",
    projectsEyebrow: "ရွေးချယ်ထားသော လက်ရာများ",
    projectsTitle: "ရည်ရွယ်ချက်နဲ့ ဖန်တီးထားပါတယ်။",
    filterAll: "အားလုံး",
    filterFrontend: "Frontend",
    filterFullstack: "Full-stack",
    previewKicker: "အေးချမ်းသော မနက်ခင်း၊ ကော်ဖီကောင်းကောင်း",
    previewShop: "မီနူးကို ကြည့်ရန်",
    previewMatch: "သင့်စိတ်ခံစားချက်၊ သင့်ကော်ဖီ",
    previewBrewMatch: "သင့်ရဲ့<br>BrewMatch ကို ရှာပါ။",
    previewFind: "သင့်ကော်ဖီကို ရှာရန်",
    previewCart: "လတ်လတ်ဆတ်ဆတ် ရွေးချယ်ထားသည်",
    previewCartTitle: "တစ်ခုခု<br>သုံးဆောင်ပါ။",
    previewCartCta: "သင့်ခြင်းတောင်း · 02",
    previousPreview: "ယခင်ပရောဂျက် အစမ်းမြင်ကွင်း",
    nextPreview: "နောက်ပရောဂျက် အစမ်းမြင်ကွင်း",
    mapCaption: "Google Maps မှတစ်ဆင့် ဒေသအရသာလေး",
    featuredLabel: "အထူးဖော်ပြထားသော ဖြစ်ရပ်လေ့လာမှု",
    projectDescription:
      "ကော်ဖီဆိုင်အတွက် စာမျက်နှာများစွာပါသော အတွေ့အကြုံတစ်ခုဖြစ်ပြီး ကိုယ်ကြိုက်မယ့် ကော်ဖီအသစ်ရှာရတာကို ပထမဆုံးသောက်တဲ့အချိန်လို ပျော်ရွှင်စေဖို့ ဖန်တီးထားပါတယ်။",
    featureDiscount:
      "လျှော့စျေး ပေါ်လာသောဝင်းဒိုးနှင့် လုပ်ဆောင်ချက် အလှည့်ကျပြသမှု",
    featureCart:
      "အပြန်အလှန်အသုံးပြုနိုင်သော ဈေးဝယ်ခြင်းတောင်းနှင့် မျက်နှာပြင်လိုက် လမ်းညွှန်မှု",
    featureBrew: "စိတ်ခံစားချက်အလိုက် ကော်ဖီရှာပေးသော BrewMatch",
    featureMap: "Google Maps ထည့်သွင်းထားမှု",
    githubCode: "GitHub",
    liveDemoSoon: "Live demo မကြာမီ",
    comingSoon: "မကြာမီလာမည်",
    nextBuildOne: "အကြံသစ်တစ်ခု ပေါ်ပေါက်နေပါတယ်။",
    nextBuildOneDesc:
      "နောက်ပရောဂျက်ကို စတင်ပုံဖော်နေပါတယ်။ မကြာမီ ပြန်လာကြည့်ပါ။",
    nextBuildTwo: "အသေးစိတ်ကို ဂရုစိုက်ထားတဲ့ အရာတစ်ခု။",
    nextBuildTwoDesc:
      "အသေးစိတ်တိုင်းကို ဂရုစိုက်ထားတဲ့ နောက်ထပ် ပရောဂျက်ငယ်တစ်ခု။",
    educationEyebrow: "အခြေခံအုတ်မြစ်",
    educationTitle: "သင်ယူမှုက တစ်ကြိမ်နဲ့ မပြီးဆုံးပါ။",
    educationLabel: "ပညာရေး",
    educationTimelineLabel: "ပညာရေးမှတ်တမ်း",
    level5Title: "NCC Education Level 5၊ Cyber Security",
    educationInProgress: "သင်ယူနေဆဲ",
    level4Title: "NCC Education Level 4 Diploma in Computing",
    educationCompleted: "ပြီးဆုံးပြီး",
    contactEyebrow: "အသုံးဝင်တာတစ်ခု ဖန်တီးကြရအောင်",
    contactTitle: "ကောင်းမွန်တဲ့အလုပ်က<br>နှုတ်ဆက်စကားနဲ့ စတင်ပါတယ်။",
    contactDescription:
      "အလုပ်သင် သို့မဟုတ် Junior Developer ရာထူးကို ရှာဖွေနေပါတယ်။ ပရောဂျက် သို့မဟုတ် အခွင့်အရေးရှိပါသလား။ ကြားသိရဖို့ ဝမ်းသာပါတယ်။",
    sendEmail: "အီးမေးလ်ပို့ရန်",
    findMe: "ဝဘ်ပေါ်မှာ ရှာတွေ့နိုင်ပါတယ်",
    emailLabel: "အီးမေးလ်",
    copyEmail: "အီးမေးလ်လိပ်စာ ကူးယူရန်",
    copiedToast: "အီးမေးလ်ကို ကူးယူပြီးပါပြီ",
    footerText: "စူးစမ်းလိုစိတ်ဖြင့် ဒီဇိုင်းဆွဲ တည်ဆောက်ထားသည်။",
    footerRights: "မူပိုင်ခွင့်အားလုံး ရယူထားသည်။",
  },
};
